sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - jruby

os:
  - linux

before_install: gem install bundler
script:
  - bundle install
  - rake spec
  - gem build ./em-midori.gemspec