language: ruby
sudo: false
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-head
  - jruby-9.0.4.0

jdk:
  - openjdk7
  - oraclejdk7

matrix:
  exclude:
    - rvm: 2.2.5
      jdk: oraclejdk7
    - rvm: 2.3.1
      jdk: oraclejdk7
  allow_failures:
    - rvm: jruby-head

os:
  - linux

before_install:
  - gem install bundler

script:
  - gem list -l
  - rake spec
  - gem build ./em-midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false