language: ruby
rvm: 2.1.0
sudo: false
matrix:
  include:
    - rvm: 2.2.6
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk7
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk8
    - rvm: jruby-9.0.4.0
      jdk: openjdk7
    - rvm: jruby-head
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: openjdk7
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3.59

os:
  - linux

services:
  - postgresql
  - redis-server

before_install:
  - gem install bundler
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - gem list -l
  - export JRUBY_OPTS="--debug"
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./em-midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
