language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - jruby

os:
  - linux

before_install:
  - gem install bundler

script:
  - rake spec
  - gem build ./em-midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false