language: ruby
sudo: false
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-head
  - jruby-9.0.4.0
  - rbx-3.20

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  exclude:
    - rvm: 2.2.5
      jdk: oraclejdk8
    - rvm: 2.3.1
      jdk: oraclejdk8
    - rvm: rbx-3.20
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3.20

os:
  - linux

before_install:
  - gem install bundler

script:
  - gem list -l
  - rake spec
  - gem build ./em-midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false